//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public TblStudent()
        {
            this.TblAttendances = new HashSet<TblAttendance>();
        }
    
        public int S_Id { get; set; }
        public string S_Name { get; set; }
    
        public virtual ICollection<TblAttendance> TblAttendances { get; set; }
    }
}
